unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

runtime! ./lightline.vim
colorscheme gruvbox
let g:terminal_ansi_colors = [
  \ "#282828", "#cc241d", "#98971a", "#d79921",
  \ "#458588", "#b16286", "#689d6a", "#a89984",
  \ "#928374", "#fb4934", "#b8bb26", "#fabd2f",
  \ "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"
  \]
set background=dark
set termguicolors

runtime! ./common.vim
